// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atwubaowirfmlydbyxvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0d3ViYW93aXJmbWx5ZGJ5eHZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDU4OTMsImV4cCI6MjA3MDQyMTg5M30.zTPqF0utynztKLwIRk8FniY9vqeFP_j5bzaL8nqLzA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});